from django.shortcuts import render,HttpResponse

# Create your views here.
def khabar(request):
    l=[
        {"onvan":"خبر اول","matn":"Lorem ipLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipiscisum dolor, sit amet consectetur adipisicing elit. Quis maiores corrupti nulla. Autem enim tenetur, inventore molestiae modi dicta eum? Fugiat rerum perspiciatis enim officiis iure accusamus ut, deleniti magnam!"},
        {"onvan":"خبر دوم","matn":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, asperiores molestiae error exercitationem porro veniam nobis delectus reiciendis nisi, esse a placeat unde architecto? Veniam tempore nisi debitis accusamus. Nobis! Lorem ipsum, dolor sit amet consectetur adipiLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipiscisicing elit. Praesentium magnam expedita libero consequatur quibusdam sed, totam impedit quis quisquam aperiam mollitia necessitatibus. Error beatae ipsum vero dolorem autem saepe iLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipiscillo?"},
        {"onvan":"خبر سوم","matn":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisci."},
        {"onvan":"خبر چهارم","matn":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam vel alias consequatur voluptate, nobis quam odio ex sunt, aliquam sapienLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipiscite voluptatem suscipit deserunt magni fugit doLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipiscilorum vitae, atque error earum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium magnam expedita libero consequatur quibusdam sed, totam impedit quis quisquam aperiam mollitia necessitatibus. Error beatae ipsum vero dolorem autem saepe illo?"},
        {"onvan":"خبر پنجم","matn":"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium magnam expedita libero consequatur quibusdam sed, totam Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciLorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis tenetur dicta quaerat, blanditiis, ea ipsum quidem cupiditate modi magnam cum unde dignissimos hic obcaecati a dolore consequuntur ducimus quos adipisciimpedit quis quisquam aperiam mollitia necessitatibus. Error beatae ipsum vero dolorem autem saepe illo?"},
    ]
    d=l[0]
    return render(request,"akhbar/akhbar.html",context={"kh":l})